create table boards (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null,
    title text
);

create table column_areas (
    id bigint generated by default as identity primary key,
    title text,
    board bigint references boards,
    sort_order integer
);

create table cards (
    id bigint generated by default as identity primary key,
    column_area bigint references column_areas,
    title text,
    sort_order integer
);

