create table boards (
    id bigint generated by default as identity primary key,
    slug text,
    user_id uuid references auth.users not null,
    title text
);

create table columns (
    id uuid default gen_random_uuid() primary key,
    name text not null,
    board_id bigint references boards(id) on delete cascade,
    sort_order integer default 0
);

create table cards (
    id bigint generated by default as identity primary key,
    name text not null,
    column_id uuid references columns(id) on delete cascade,
    sort_order integer default 0
);